### ISSUE TITLE
Can't sign in to run app

### ISSUE THREAD

**Issue by aaronrobb** [mithunmanohar/woocommerce-orders-google-sheets-integration#38]
When trying out this app, I set it up on my account, then click the 'Sync' button, and it comes up saying "Authorization Required - A script attached to this document needs your permission to run.", so i click Authorize, log into my Google account and the screen then says:
"Sign in with Google temporarily disabled for this app.
This app has not been verified yet by Google in order to use Google Sign In."

So googling it, and looking through the issues here, it looks like we need to verify the app. But to verify, it sends me to the Google Cloud platform, and that's where I'm not sure what to do. I have projects there, but none associated with this one - and I'm not sure how to associate a Sheets Script with a project....

Anyone able to do this and can direct me in the proper procedure?

**Comment by mithunmanohar** [comment]
This is a known behavior - and the details are mentioned the 3rd point of documentation here https://github.com/mithunmanohar/woocommerce-orders-google-sheets-integration/blob/master/README.md
_It will show the app as unverified - This is because it is trying to access an external URL - the site you have given in the sheet in this case. Click on Advanced and proceed. Please feel free to take a look at the code in the script editor to see what the sheet is doing in case you are in doubt._

**Comment by aaronrobb** [comment]
@mithunmanohar Thanks for the reply.
I don't have an option for 'Advanced' in that error popup.
Shows nothing beyond the message in the popup.

**Comment by mithunmanohar** [comment]
Are you using G-suite by any chance? I checked with a normal Gmail address and confirm its working.
![Capture](https://user-images.githubusercontent.com/10810426/81970607-6d59e200-963d-11ea-9fa7-d86467362364.PNG)

**Comment by mithunmanohar** [comment]
Closing this issue as there is no follow up.

**Comment by srjlulla** [comment]
Just used a Gsuite account and it started working, got the "Advanced" link
